services:
  emqx:
    image: emqx:5.8.7
    container_name: emqx
    ports:
      - "1883:1883"     # MQTT
      - "8083:8083"     # MQTT over WebSocket
      - "18083:18083"   # EMQX dashboard
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
  
  api:
    build: ./mern-backend
    container_name: api
    environment:
      - MONGO_URI=mongodb://mongo:27017/esp_gateway
      - MQTT_URL=mqtt://emqx:1883
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3000"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./mern-backend/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - emqx
      - mongo


volumes:
  mongo_data: